[package]
name = "pancakes"
version = "0.1.0"
authors = ["abhro <abhro@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro/hello_macro_derive" }
